export const ADD_TODO = 'ADD_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const EDIT_TODO = 'EDIT_TODO';
export const COMPLETE_TODO = 'COMPLETE_TODO';
export const COMPLETE_ALL = 'COMPLETE_ALL';
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED';

export const REQUEST_ALL_FLIGHTS = 'REQUEST_ALL_FLIGHTS';
export const RECEIVE_ALL_FLIGHTS = 'RECEIVE_ALL_FLIGHTS';
export const SET_CARRIER_FILTER = 'SET_CARRIER_FILTER';
export const REQUEST_FILTERED_FLIGHTS = 'REQUEST_FILTERED_FLIGHTS';
export const REQUEST_CARRIERS = 'REQUEST_CARRIERS';